### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by mlhale7** [cmharlow/geonames-reconcile#11]
Not sure if you're still keeping this up, but I'm currently getting the following error when attempting to run 127.0.0.1 "GET / HTTP/1.1" 404. Is this reconciliation service still functional or is it something on my end? I'm using it with python 2.7.

**Comment by cmharlow** [comment]
Try `127.0.0.1/recon`

**Comment by mlhale7** [comment]
I wanted to follow up and say that using 'http://localhost:5000/reconcile' did address this issue. Apologies for leaving this open.
